/* automatically generated by rust-bindgen 0.72.1 */

pub const VLLM_ABI_VERSION: u32 = 17;
pub const vllm_status_VLLM_OK: vllm_status = 0;
pub const vllm_status_VLLM_ERR_INVALID_ARGUMENT: vllm_status = 1;
pub const vllm_status_VLLM_ERR_MODEL_LOAD: vllm_status = 2;
pub const vllm_status_VLLM_ERR_RUNTIME: vllm_status = 3;
pub const vllm_status_VLLM_ERR_UNKNOWN: vllm_status = 4;
pub type vllm_status = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_engine {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_request {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_model_params {
    pub model_path: *const ::std::os::raw::c_char,
    pub tokenizer_config_path: *const ::std::os::raw::c_char,
    pub block_size: i32,
    pub num_blocks: i32,
    pub max_model_len: i32,
    pub max_num_seqs: i32,
    pub tool_parser: *const ::std::os::raw::c_char,
    pub reasoning_parser: *const ::std::os::raw::c_char,
    pub speculative_config: *const ::std::os::raw::c_char,
    pub enable_prefix_caching: i32,
    pub max_num_batched_tokens: i32,
    pub scheduling_policy: *const ::std::os::raw::c_char,
    pub kv_transfer_config: *const ::std::os::raw::c_char,
    pub enable_jump_forward: i32,
    pub device: i32,
    pub gpu_memory_utilization: f64,
    pub kv_cache_memory_bytes: i64,
}
pub type vllm_logits_processor = ::std::option::Option<
    unsafe extern "C" fn(
        token_ids: *const i32,
        n_token_ids: i32,
        logits: *mut f32,
        vocab_size: i32,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_sampling_params {
    pub temperature: f32,
    pub top_p: f32,
    pub top_k: i32,
    pub min_p: f32,
    pub max_tokens: i32,
    pub seed: u64,
    pub has_seed: i32,
    pub presence_penalty: f32,
    pub frequency_penalty: f32,
    pub repetition_penalty: f32,
    pub min_tokens: i32,
    pub ignore_eos: i32,
    pub stop: *const *const ::std::os::raw::c_char,
    pub n_stop: i32,
    pub structured_json: *const ::std::os::raw::c_char,
    pub structured_regex: *const ::std::os::raw::c_char,
    pub structured_choice: *const *const ::std::os::raw::c_char,
    pub n_structured_choice: i32,
    pub structured_grammar: *const ::std::os::raw::c_char,
    pub structured_json_object: i32,
    pub logits_processor: vllm_logits_processor,
    pub logits_processor_user_data: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_completion {
    pub text: *mut ::std::os::raw::c_char,
    pub finish_reason: *const ::std::os::raw::c_char,
    pub prompt_tokens: i32,
    pub completion_tokens: i32,
}
unsafe extern "C" {
    pub fn vllm_model_params_default() -> vllm_model_params;
}
unsafe extern "C" {
    pub fn vllm_sampling_params_default() -> vllm_sampling_params;
}
unsafe extern "C" {
    pub fn vllm_engine_load(
        params: *const vllm_model_params,
        out: *mut *mut vllm_engine,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_engine_free(engine: *mut vllm_engine);
}
unsafe extern "C" {
    pub fn vllm_complete(
        engine: *mut vllm_engine,
        prompt: *const ::std::os::raw::c_char,
        params: *const vllm_sampling_params,
        out: *mut vllm_completion,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_complete_tokens(
        engine: *mut vllm_engine,
        prompt_tokens: *const i32,
        n_prompt_tokens: i32,
        params: *const vllm_sampling_params,
        out_tokens: *mut i32,
        max_out_tokens: i32,
        n_out_tokens: *mut i32,
        out: *mut vllm_completion,
    ) -> vllm_status;
}
pub type vllm_token_callback = ::std::option::Option<
    unsafe extern "C" fn(
        delta_text: *const ::std::os::raw::c_char,
        finished: bool,
        user_data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
unsafe extern "C" {
    pub fn vllm_complete_stream(
        engine: *mut vllm_engine,
        prompt: *const ::std::os::raw::c_char,
        params: *const vllm_sampling_params,
        cb: vllm_token_callback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_request_submit(
        engine: *mut vllm_engine,
        prompt: *const ::std::os::raw::c_char,
        params: *const vllm_sampling_params,
        cb: vllm_token_callback,
        user_data: *mut ::std::os::raw::c_void,
        out: *mut *mut vllm_request,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_request_cancel(request: *mut vllm_request) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_request_wait(request: *mut vllm_request) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_request_done(request: *const vllm_request) -> bool;
}
unsafe extern "C" {
    pub fn vllm_request_error(request: *const vllm_request) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn vllm_request_free(request: *mut vllm_request);
}
unsafe extern "C" {
    pub fn vllm_chat(
        engine: *mut vllm_engine,
        request_json: *const ::std::os::raw::c_char,
        out_response_json: *mut *mut ::std::os::raw::c_char,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_chat_stream(
        engine: *mut vllm_engine,
        request_json: *const ::std::os::raw::c_char,
        cb: vllm_token_callback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> vllm_status;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_transcription_params {
    pub audio_path: *const ::std::os::raw::c_char,
    pub pcm: *const f32,
    pub n_samples: i64,
    pub sample_rate: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_transcription {
    pub text: *mut ::std::os::raw::c_char,
    pub token_ids: *mut i32,
    pub n_token_ids: i32,
    pub has_text: i32,
}
unsafe extern "C" {
    pub fn vllm_transcription_params_default() -> vllm_transcription_params;
}
unsafe extern "C" {
    pub fn vllm_transcribe(
        engine: *mut vllm_engine,
        params: *const vllm_transcription_params,
        out: *mut vllm_transcription,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_transcription_free(out: *mut vllm_transcription);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_embedding_result {
    pub values: *mut f32,
    pub n_embeddings: i32,
    pub dim: i32,
    pub prompt_tokens: i32,
}
unsafe extern "C" {
    pub fn vllm_embed(
        engine: *mut vllm_engine,
        texts: *const *const ::std::os::raw::c_char,
        n_texts: i32,
        out: *mut vllm_embedding_result,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_embedding_result_free(out: *mut vllm_embedding_result);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_video_engine {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_video_model_params {
    pub dit_path: *const ::std::os::raw::c_char,
    pub encoder_path: *const ::std::os::raw::c_char,
    pub tokenizer_path: *const ::std::os::raw::c_char,
    pub video_vae_path: *const ::std::os::raw::c_char,
    pub video_vae_config_path: *const ::std::os::raw::c_char,
    pub audio_vae_path: *const ::std::os::raw::c_char,
    pub audio_vae_config_path: *const ::std::os::raw::c_char,
    pub prompt_embeds_path: *const ::std::os::raw::c_char,
    pub partition: *const ::std::os::raw::c_char,
    pub device: i32,
    pub dequant_bf16: i32,
    pub fp4_resident: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_video_params {
    pub prompt: *const ::std::os::raw::c_char,
    pub width: i32,
    pub height: i32,
    pub num_frames: i32,
    pub steps: i32,
    pub seed: u64,
    pub has_seed: i32,
    pub first_frame: *const ::std::os::raw::c_char,
    pub last_frame: *const ::std::os::raw::c_char,
    pub ref_image: *const ::std::os::raw::c_char,
    pub ref_video: *const ::std::os::raw::c_char,
    pub ref_audio: *const ::std::os::raw::c_char,
    pub noise_aug: f32,
    pub output_dir: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_video_result {
    pub frame_dir: *mut ::std::os::raw::c_char,
    pub audio_path: *mut ::std::os::raw::c_char,
    pub frame_count: i32,
    pub width: i32,
    pub height: i32,
    pub fps: i32,
    pub sample_rate: i32,
    pub mux_argv: *mut *mut ::std::os::raw::c_char,
    pub mux_argc: i32,
}
unsafe extern "C" {
    pub fn vllm_video_model_params_default() -> vllm_video_model_params;
}
unsafe extern "C" {
    pub fn vllm_video_params_default() -> vllm_video_params;
}
unsafe extern "C" {
    pub fn vllm_video_engine_load(
        params: *const vllm_video_model_params,
        out: *mut *mut vllm_video_engine,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_video_engine_free(engine: *mut vllm_video_engine);
}
unsafe extern "C" {
    pub fn vllm_video_generate(
        engine: *mut vllm_video_engine,
        params: *const vllm_video_params,
        out: *mut vllm_video_result,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_video_result_free(out: *mut vllm_video_result);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_video_mux_params {
    pub frames: *const ::std::os::raw::c_char,
    pub audio_path: *const ::std::os::raw::c_char,
    pub output_path: *const ::std::os::raw::c_char,
    pub fps: i32,
    pub crf: i32,
}
unsafe extern "C" {
    pub fn vllm_video_mux_params_default() -> vllm_video_mux_params;
}
unsafe extern "C" {
    pub fn vllm_video_mux_argv(
        params: *const vllm_video_mux_params,
        out_argv: *mut *mut *mut ::std::os::raw::c_char,
        out_argc: *mut i32,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_video_mux_argv_free(argv: *mut *mut ::std::os::raw::c_char, argc: i32);
}
unsafe extern "C" {
    pub fn vllm_string_free(s: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn vllm_completion_free(out: *mut vllm_completion);
}
unsafe extern "C" {
    pub fn vllm_last_error() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn vllm_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn vllm_server_main(argc: i32, argv: *mut *mut ::std::os::raw::c_char) -> i32;
}
unsafe extern "C" {
    pub fn vllm_abi_version() -> i32;
}
