/* automatically generated by rust-bindgen 0.72.1 */

pub const VLLM_ABI_VERSION: u32 = 10;
pub const vllm_status_VLLM_OK: vllm_status = 0;
pub const vllm_status_VLLM_ERR_INVALID_ARGUMENT: vllm_status = 1;
pub const vllm_status_VLLM_ERR_MODEL_LOAD: vllm_status = 2;
pub const vllm_status_VLLM_ERR_RUNTIME: vllm_status = 3;
pub const vllm_status_VLLM_ERR_UNKNOWN: vllm_status = 4;
pub type vllm_status = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_engine {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_request {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_model_params {
    pub model_path: *const ::std::os::raw::c_char,
    pub tokenizer_config_path: *const ::std::os::raw::c_char,
    pub block_size: i32,
    pub num_blocks: i32,
    pub max_model_len: i32,
    pub max_num_seqs: i32,
    pub tool_parser: *const ::std::os::raw::c_char,
    pub reasoning_parser: *const ::std::os::raw::c_char,
    pub speculative_config: *const ::std::os::raw::c_char,
    pub enable_prefix_caching: i32,
    pub max_num_batched_tokens: i32,
    pub scheduling_policy: *const ::std::os::raw::c_char,
    pub kv_transfer_config: *const ::std::os::raw::c_char,
    pub enable_jump_forward: i32,
}
pub type vllm_logits_processor = ::std::option::Option<
    unsafe extern "C" fn(
        token_ids: *const i32,
        n_token_ids: i32,
        logits: *mut f32,
        vocab_size: i32,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_sampling_params {
    pub temperature: f32,
    pub top_p: f32,
    pub top_k: i32,
    pub min_p: f32,
    pub max_tokens: i32,
    pub seed: u64,
    pub has_seed: i32,
    pub presence_penalty: f32,
    pub frequency_penalty: f32,
    pub repetition_penalty: f32,
    pub min_tokens: i32,
    pub ignore_eos: i32,
    pub stop: *const *const ::std::os::raw::c_char,
    pub n_stop: i32,
    pub structured_json: *const ::std::os::raw::c_char,
    pub structured_regex: *const ::std::os::raw::c_char,
    pub structured_choice: *const *const ::std::os::raw::c_char,
    pub n_structured_choice: i32,
    pub structured_grammar: *const ::std::os::raw::c_char,
    pub structured_json_object: i32,
    pub logits_processor: vllm_logits_processor,
    pub logits_processor_user_data: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vllm_completion {
    pub text: *mut ::std::os::raw::c_char,
    pub finish_reason: *const ::std::os::raw::c_char,
    pub prompt_tokens: i32,
    pub completion_tokens: i32,
}
unsafe extern "C" {
    pub fn vllm_model_params_default() -> vllm_model_params;
}
unsafe extern "C" {
    pub fn vllm_sampling_params_default() -> vllm_sampling_params;
}
unsafe extern "C" {
    pub fn vllm_engine_load(
        params: *const vllm_model_params,
        out: *mut *mut vllm_engine,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_engine_free(engine: *mut vllm_engine);
}
unsafe extern "C" {
    pub fn vllm_complete(
        engine: *mut vllm_engine,
        prompt: *const ::std::os::raw::c_char,
        params: *const vllm_sampling_params,
        out: *mut vllm_completion,
    ) -> vllm_status;
}
pub type vllm_token_callback = ::std::option::Option<
    unsafe extern "C" fn(
        delta_text: *const ::std::os::raw::c_char,
        finished: bool,
        user_data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
unsafe extern "C" {
    pub fn vllm_complete_stream(
        engine: *mut vllm_engine,
        prompt: *const ::std::os::raw::c_char,
        params: *const vllm_sampling_params,
        cb: vllm_token_callback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_request_submit(
        engine: *mut vllm_engine,
        prompt: *const ::std::os::raw::c_char,
        params: *const vllm_sampling_params,
        cb: vllm_token_callback,
        user_data: *mut ::std::os::raw::c_void,
        out: *mut *mut vllm_request,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_request_cancel(request: *mut vllm_request) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_request_wait(request: *mut vllm_request) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_request_done(request: *const vllm_request) -> bool;
}
unsafe extern "C" {
    pub fn vllm_request_error(request: *const vllm_request) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn vllm_request_free(request: *mut vllm_request);
}
unsafe extern "C" {
    pub fn vllm_chat(
        engine: *mut vllm_engine,
        request_json: *const ::std::os::raw::c_char,
        out_response_json: *mut *mut ::std::os::raw::c_char,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_chat_stream(
        engine: *mut vllm_engine,
        request_json: *const ::std::os::raw::c_char,
        cb: vllm_token_callback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> vllm_status;
}
unsafe extern "C" {
    pub fn vllm_string_free(s: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn vllm_completion_free(out: *mut vllm_completion);
}
unsafe extern "C" {
    pub fn vllm_last_error() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn vllm_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn vllm_abi_version() -> i32;
}
